# Ficheiro de configuração para o Railway (Nixpacks)

[phases.setup]
nixPkgs = ["pkgs.cairo", "pkgs.pango", "pkgs.gdk-pixbuf", "pkgs.pkg-config", "pkgs.libffi", "pkgs.liberation_ttf", "pkgs.fontconfig", "pkgs.gcc"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT --workers 4"
